                      


#? POST - /api/auth/signup - This endpoint allows users to register. Hash the password on store.✅                              
POST http://localhost:3000/auth/signup
Content-Type: application/json

# {
#     "name":"Kunal Mehra",
#     "email":"k@gmail.com",
#     "password":"kunal@143"
# }

{
    "name":"Vanshika Mehra",
    "email":"v@gmail.com",
    "password":"v@143"
}

###

#? POST - /api/auth/login - This endpoint allows users to login through email and password ✅                                   
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email":"v@gmail.com",
    "password":"v@143"
}

###

#? GET -  /api/users - This endpoint returns a list of all registered users.✅    
GET http://localhost:3000/users
### 


#? POST - /api/users/follow/:id - This endpoint returns a list of all followed people of a specific user identified by its ID.
POST http://localhost:3000/users/follow/64770c019526193ee2c6e123
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2NDc3MGMyYjk1MjYxOTNlZTJjNmUxMjkiLCJpYXQiOjE2ODU1MjM1MDl9.GhQuqCqV4waGNcpCHRjQe9zj_-AIm-039JD5JT-6fBs
###

#? POST - /api/users/unfollow/:id - This endpoint allows the user to send a follow request to another user identified by its ID. 
POST http://localhost:3000/users/unfollow/64770c019526193ee2c6e123 
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2NDc3MGMyYjk1MjYxOTNlZTJjNmUxMjkiLCJpYXQiOjE2ODU1MjM1MDl9.GhQuqCqV4waGNcpCHRjQe9zj_-AIm-039JD5JT-6fBs

###

#? GET - /api/posts - This endpoint returns a list of all posts.                                                         
GET http://localhost:3000/posts
###

#? GET - /api/posts/:id - This endpoint returns the details of a specific post identified by its ID.      
GET http://localhost:3000/posts/647707f5c6807500c7e889bb
###

#? POST - /api/posts - This endpoint allows the user to create a new post.                             
POST http://localhost:3000/posts
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2NDc3MDNiOWY2ZWQzOThlMzFiYjY3NDYiLCJpYXQiOjE2ODU1MjE4NTV9.ekGeo6g14h4g0s6YI4WTxSc90MPObuR0IvWliUoCALw

{
    "Title":"Hello this is Test Post 2",
    "Content":"lorem othelloo"
}

###

#? POST - /api/posts/like/:id - This endpoint allows users to like a specific post identified by its ID.  
POST http://localhost:3000/posts/like/647707f5c6807500c7e889bb
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2NDc3MDNiOWY2ZWQzOThlMzFiYjY3NDYiLCJpYXQiOjE2ODU1MjE4NTV9.ekGeo6g14h4g0s6YI4WTxSc90MPObuR0IvWliUoCALw

###

#? POST - /api/posts/comment/:id - This endpoint allows users to comment on a specific post identified by its ID. 
POST http://localhost:3000/comment/647707f5c6807500c7e889bb
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2NDc3MDNiOWY2ZWQzOThlMzFiYjY3NDYiLCJpYXQiOjE2ODU1MjE4NTV9.ekGeo6g14h4g0s6YI4WTxSc90MPObuR0IvWliUoCALw

###

#? PUT - /api/posts/:id - This endpoint allows users to update the text or image of a specific post identified by its ID.   
PUT http://localhost:3000/posts/647707f5c6807500c7e889bb
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2NDc3MDNiOWY2ZWQzOThlMzFiYjY3NDYiLCJpYXQiOjE2ODU1MjE4NTV9.ekGeo6g14h4g0s6YI4WTxSc90MPObuR0IvWliUoCALw

{
    "Title":"This is a New Title"
}

###

#? DELETE - /api/posts/:id - This endpoint allows users to delete a specific post identified by its ID.       
DELETE http://localhost:3000/posts/647707f5c6807500c7e889bb
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2NDc3MDNiOWY2ZWQzOThlMzFiYjY3NDYiLCJpYXQiOjE2ODU1MjE4NTV9.ekGeo6g14h4g0s6YI4WTxSc90MPObuR0IvWliUoCALw

###